version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: clearenroll_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - clearenroll_net

  backend:
    image: kwakujnr/clearenroll-backend:latest
    container_name: clearenroll_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env.prod
    volumes:
      - backend_uploads:/app/uploads
    networks:
      - clearenroll_net

  frontend:
    image: kwakujnr/clearenroll-frontend:latest
    container_name: clearenroll_frontend
    restart: unless-stopped
    networks:
      - clearenroll_net

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - clearenroll_net

  watchtower:
    image: containrrr/watchtower:1.7.1
    container_name: clearenroll_watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    networks:
      - clearenroll_net

networks:
  clearenroll_net:

volumes:
  mysql_data:
  backend_uploads:
  npm_data:
  npm_letsencrypt: