server {
  listen 80;

  location / {
    proxy_pass http://frontend:80;
  }

  location /api/ {
    proxy_pass http://backend:4000/;
  }

  location /uploads/ {
    proxy_pass http://backend:4000/uploads/;
  }

  client_max_body_size 50M;
}